### ISSUE TITLE
Errors due to incomplete search-replace

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/site-command#153]
Running  `ee site list --enabled` throws following error - 
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: is_enabled in phar:///usr/local/bin/ee/php/class-ee-db.php:114
Stack trace:
#0 phar:///usr/local/bin/ee/php/class-ee-db.php(114): PDO->prepare('SELECT * FROM s...')
#1 phar:///usr/local/bin/ee/php/class-ee-db.php(286): EE_DB->common_retrieval_function()
#2 phar:///usr/local/bin/ee/php/class-ee-db.php(275): EE_DB->get()
#3 phar:///usr/local/bin/ee/php/EE/Model/Base.php(180): EE_DB->all()
#4 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(105): EE\Model\Base::where('is_enabled', true)
#5 [internal function]: EE\Site\Type\EE_Site_Command->_list(Array, Array)
#6 phar:///usr/local/bin/ee/php/EE/Dispatcher/CommandFactory.php(96): call_user_func(Array, Array, Array)
#7 [internal function]: EE\Dispatcher\CommandFactory::EE\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/local/bin/ee/php/EE/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#9 phar:///usr/local/bin/ee/php/EE/Runner in phar:///usr/local/bin/ee/php/class-ee-db.php on line 114
Warning: An Error occurred. Initiating clean-up.
Warning: Exiting gracefully after rolling back. This may take some time.
Success: Rollback complete. Exiting now.
```

To fix it, we have to replace `is_enabled` to `site_enabled` in https://github.com/EasyEngine/site-command/blob/develop/src/helper/class-ee-site.php#L105 and https://github.com/EasyEngine/site-command/blob/develop/src/helper/class-ee-site.php#L107

**Comment by mrrobot47** [comment]
This issue occurred due to the changes in db fields done in EasyEngine/easyengine#1143 were not properly replaced at all the places they were being used in code. 

@sagarnasit as you're working on it. Please recheck all the changes in db field names and if they have been searched and replaced properly or not across packages.

For example, even the old db field `sitename` that has been changed to `site_url` is still there in the current codebase like [here](https://github.com/EasyEngine/easyengine/blob/9c3571d671d001d6f3efd54d43ba1d8cb491461d/php/EE/Migration/Containers.php#L71).
