### ISSUE TITLE
Remove limit of 27 sites per server

### ISSUE THREAD

**Issue by gwizards** [EasyEngine/site-command#385]
Do you know if there is any manual way to disable this limit? I have a pretty big server where I want to host more than 27 sites.

Thank you!

**Comment by kirtangajjar** [comment]
Hey @gwizards, we have identified the fix for it and it's in our pipeline, but still, it would take some time for it to get fixed. I'm afraid there's no manual fix for it as it requires changing of docker network creation logic.
 
There are some old PRs lying around that you can try and build a custom PHAR, but I'm not sure if it would work. Also, I won't be able to help much with debugging it further due to my limited time. If you still want to go ahead, try your luck with https://github.com/EasyEngine/site-command/pull/282 and https://github.com/EasyEngine/service-command/pull/49

**Comment by gwizards** [comment]
Prefers to wait for the official release. Can I help in any way with this feature?

**Comment by kirtangajjar** [comment]
@gwizards the best you can do is to test both the above PRs in your machine/some other server and let us know if you find any issues.

**Comment by L0RD-ZER0** [comment]
This issue has been resolved in newer EasyEngine releases.. Please update EasyEngine to the latest version using ``ee cli update`` command.  In order for a fresh installation instead, consider using the command ``wget -qO ee rt.cx/ee4 && sudo bash ee`` to use the automated installation script to install the latest version of EasyEngine.
